# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather forecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather forecast
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire'
  pod "SwiftSpinner"
  
end
